# -*- encoding: utf-8 -*-

lib = File.expand_path('../lib/', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'rack/decorator'

Gem::Specification.new do |s|
  s.name          = 'rack-decorator'
  s.version       = Rack::Decorator::VERSION
  s.summary       = 'Rack middleware to modify HTML content generated by other apps in the Rack stack.'

  s.author        = 'John Labovitz'
  s.email         = 'johnl@johnlabovitz.com'
  s.description   = %q{
    Rack::Decorator is Rack middleware to modify HTML content generated by other apps in the Rack stack.
    
    More information to come.
  }
  s.homepage      = 'http://github.com/jslabovitz/rack-decorator'

  s.add_dependency  'rack'
  s.add_dependency  'nokogiri'
  
  s.files        = Dir.glob('{bin,lib,test}/**/*') + %w(README.markdown)
  s.require_path = 'lib'
end